### ISSUE TITLE
ArgumentOutOfRangeException when time range is less than 25 minutes

### ISSUE THREAD

**Issue by vicprepr** [Live-Charts/Live-Charts#1039]
#### How to reproduce?

Create a CartesianChart with one axis X.
Set Binding of MinValue and MaxValue properties of this Axis X to double properties of the ViewModel.
Add one GLineSeries with DateTimePoint values.
Create two UI controls (TimePicker, Clock, etc) to manage "From" and "Until" times.
When the user selects the "From"/"Until" time, set the MinValue/MaxValue property in ViewModel with the proper ticks.
If time range is greater than or equals to 25 minutes, all is fine, but, if time range is less than 25 minutes, library crash with the following exception:

MESSAGE: Specified argument was out of the range of valid values.
Parameter name: index
    STACK TRACE:    at MS.Utility.FrugalStructList`1.Insert(Int32 index, T value)
   at System.Windows.Media.PathSegmentCollection.Insert(Int32 index, PathSegment value)
   at LiveCharts.Wpf.LineSeries.EndSegment(Int32 atIndex, CorePoint location)
   at LiveCharts.SeriesAlgorithms.LineAlgorithm.Update()
   at LiveCharts.ChartUpdater.Update(Boolean restartsAnimations, Boolean force)
   at LiveCharts.Wpf.Components.ChartUpdater.UpdaterTick(Boolean restartView, Boolean force)
   at System.Windows.Threading.DispatcherTimer.FireTick(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

#### I am using

<table>
<tr>
    <td>Library version</td>
    <td>LiveCharts 0.9.7</td>
    <td>LiveCharts.Wpf 0.9.7</td>
    <td>LiveCharts.Geared 1.2.9</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>4.5</td>
</tr>
<tr>
    <td>Windows</td>
    <td>10</td>
</tr>
</table>

**Comment by istvanns** [comment]
I had the problem of getting this exception when zooming out too much. In such case, the x-axis value formatter received a negative value, which breaks DateTime. So in the value formatter, I test the value and if negative, pass 0. Don't know if it helps, but that was the solution for me.

```
// this throws the exception if val is negative
XFormatter = val => new DateTime((long)val).ToString("HH:mm:ss");
// solved it by testing the value and passing 0 if negative
XFormatter = val => val < 0.0 ? (new DateTime((long)0.0).ToString("HH:mm:ss")) : (new DateTime((long)val).ToString("HH:mm:ss"));
```
