### ISSUE TITLE
ArgumentOutOfRangeException when using geared GLineSeries - minimal example

### ISSUE THREAD

**Issue by gilerez01** [Live-Charts/Live-Charts#1041]
#### How to reproduce?

•	Create a CartesianChart in Grid with Width="500"
•	Add one GLineSeries with 4 points all Y's are 1, Xs: 60, 65.1, 65, 70
•	Run. The program crashes before the window is opened.
•	Change Grid's Width="550" - no crash.
•	Change 2nd points X to 65.2 – no crash.

#### Extra notes

The exception received:
System.ArgumentOutOfRangeException
  HResult=0x80131502
  Message=Specified argument was out of the range of valid values.
Parameter name: index
  Source=WindowsBase
  StackTrace:
   at MS.Utility.FrugalStructList`1.Insert(Int32 index, T value)
   at System.Windows.Media.PathSegmentCollection.Insert(Int32 index, PathSegment value)
   at LiveCharts.Wpf.Points.HorizontalBezierPointView.DrawOrMove(ChartPoint previousDrawn, ChartPoint current, Int32 index, ChartCore chart)
   at LiveCharts.SeriesAlgorithms.LineAlgorithm.Update()
   at LiveCharts.ChartUpdater.Update(Boolean restartsAnimations, Boolean force)
   at LiveCharts.Wpf.Components.ChartUpdater.UpdaterTick(Boolean restartView, Boolean force)
   at LiveCharts.Wpf.Components.ChartUpdater.OnTimerOnTick(Object sender, EventArgs args)
   at System.Windows.Threading.DispatcherTimer.FireTick(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at LiveChartsGearedTestApp.App.Main()

MainWindow.xaml.cs

    public partial class MainWindow : Window
    {
        public SeriesCollection SeriesCollectionObj { get; set; }
        public MainWindow()
        {
            InitializeComponent();
            var gearedValues = GetValuesGeared();

            var series = new GLineSeries();
            series.Values = gearedValues;
            SeriesCollectionObj = new SeriesCollection();
            SeriesCollectionObj.Add(series);

            DataContext = this;
        }

        private static double[] values = { 60, 65.1, 65, 70 };
        public static GearedValues<ObservablePoint> GetValuesGeared()
        {
            var values1 = new ChartValues<ObservablePoint>();
            for (int i = 0; i < values.Length; i++)
            {
                values1.Add(new ObservablePoint(values[i], 1));
            }

            GearedValues<ObservablePoint> gearedValues = values1.AsGearedValues().WithQuality(Quality.Medium);
            return gearedValues;
        }

    }

MainWindow.xaml

    <Grid Width="500" >
        <lcwpf:CartesianChart
            >
            <lcwpf:CartesianChart.Series>
                <Binding Path="SeriesCollectionObj"/>
            </lcwpf:CartesianChart.Series>
        </lcwpf:CartesianChart>
    </Grid>

#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>0.9.7</td>
</tr>
<tr>
    <td>Live-Charts-Geared version</td>
    <td>1.2.9</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>4.5</td>
</tr>
<tr>
    <td>Windows</td>
    <td>10 & 7</td>
</tr>
</table>

[LiveChartsGearedTestAppWithoutPackages.zip](https://github.com/Live-Charts/Live-Charts/files/4126846/LiveChartsGearedTestAppWithoutPackages.zip)

**Comment by claudio-g** [comment]
I have the exact same issue, we also have licensed the Geared, however the problem happens also when not using the Geared package.

The below code throws the exact same exception with the exact same stack trace.
Any time 2 values in the myValues list are the same the code throws. If I change one of the 7 to 7.5, no problem.

The other weird thing is that the same list without using a custom class with mapper (i.e. new ChartValues<double>) works also perfectly fine

The offending code for me is the following

        private void Window_Loaded(object sender, RoutedEventArgs e)
        {
            SeriesCollection l_Series_Collection = new SeriesCollection();

            var myValues = new ChartValues<Tuple<double, string>>
            {
                new Tuple<double, string>(10, "TEST"), //index 0
                new Tuple<double, string>(6, "TEST"),  //index 1
                new Tuple<double, string>(9, "TEST"),  //index 2
                new Tuple<double, string>(2, "TEST"),  //index 3
                new Tuple<double, string>(7, "TEST"),   //index 4
                new Tuple<double, string>(7, "TEST"),   //index 5
                new Tuple<double, string>(4, "TEST"),  //index 6
            };

            var l_Mapper = Mappers.Xy<Tuple<double, string>>().X((param, idx) => idx).Y((param, idx) => param.Item1);

            LineSeries l_Series = new LineSeries(l_Mapper);

            l_Series.Values = myValues;

            l_Series_Collection.Add(l_Series);

            myChart.Series = l_Series_Collection;
        }
