### ISSUE TITLE
UWP Crash when changing series binding

### ISSUE THREAD

**Issue by bizzehdee** [Live-Charts/Live-Charts#741]
#### How to reproduce?

Create a new chart with binding to a model (i used a presenter and a converter)

`<lvc:CartesianChart Grid.Column="1" Series="{Binding TimeInHeartRateZones, Converter={StaticResource TimeInZonesToSeries}}"></lvc:CartesianChart>`

Change `TimeInHeartRateZones` and fire `RaisePropertyChangedEvent`.

Throws exception (but not always)

#### Exception Message

System.Runtime.InteropServices.COMException: No installed components were detected.

Element is already the child of another element.
   at System.Runtime.InteropServices.WindowsRuntime.IVector`1.Append(T value)
   at System.Runtime.InteropServices.WindowsRuntime.VectorToCollectionAdapter.Add[T](T item)
   at LiveCharts.Uwp.Charts.Base.Chart.AddToView(Object element)
   at LiveCharts.Uwp.Charts.Base.Chart.<>c__DisplayClass149_0.<MapXAxes>b__0(Axis x)
   at System.Linq.Enumerable.SelectIListIterator`2

#### Stack

   at System.Runtime.InteropServices.WindowsRuntime.IVector`1.Append(T value)
   at System.Runtime.InteropServices.WindowsRuntime.VectorToCollectionAdapter.Add[T](T item)
   at LiveCharts.Uwp.Charts.Base.Chart.AddToView(Object element)
   at LiveCharts.Uwp.Charts.Base.Chart.<>c__DisplayClass149_0.<MapXAxes>b__0(Axis x)
   at System.Linq.Enumerable.SelectIListIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at LiveCharts.Uwp.Charts.Base.Chart.MapXAxes(ChartCore chart)
   at LiveCharts.ChartUpdater.Update(Boolean restartsAnimations)
   at LiveCharts.Uwp.Components.ChartUpdater.UpdaterTick(Boolean restartView)
   at LiveCharts.Uwp.Components.ChartUpdater.<.ctor>b__0_0(Object sender, Object args)
   at Windows.ApplicationModel.Core.UnhandledError.Propagate()

#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>nuget 0.8.0</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>UWP 16299</td>
</tr>
<tr>
    <td>Windows</td>
    <td>10 Fall Creators Update</td>
</tr>
</table>

**Comment by beto-rodriguez** [comment]
Hi

Thank you for your report!.

UWP version is not updated due the current design makes it hard to keep all the projects updated.

That is why we are working to release version 1.0, this version will make it easier to keep all the versions updated, I hope the UWP version to be ready by April 18.

**Comment by bizzehdee** [comment]
0.9.5 builds fine, and https://github.com/Live-Charts/Live-Charts/pull/694 fixes the issue i am having.

Would it be possible to merge the PR in and produce a nuget package with it in? Even if it is a fix to the currently available 0.8.0.
