### ISSUE TITLE
Exceptions when Dealing with Sections

### ISSUE THREAD

**Issue by Mrxx99** [Live-Charts/Live-Charts#854]
I have two problems with the AxisSections, don't know if they are related.

1. I have a Cartesian Chart inside a not expanded expander. When setting the data, after setting the Mapper and clearing the VisualElements, I clear the Axis Sections: `axisx?.Sections?.Clear();`.
Then I set the SeriesData and the sections using `axisx.Sections.Add(new AxisSection{ ...`
When I start this process again for the same chart. I get an ArgumentNullException at the Line where I clear the Sections. But neither the axis nor the sections are null.

The strange thing is, after catching the exception and not setting the series data, if I start the process again it will again throw that exception on the same line. The next time again it won't and so on.

But If I first expand the expander and the reload the data again all works fine.

Here is the stacktrace without the calling of my code:

>    at LiveCharts.Wpf.AxisSection.Remove() in c:\Users\btord\Documents\Projects\LiveCharts\WpfView\AxisSection.cs:Zeile 392.
>    at LiveCharts.Wpf.SectionsCollection.OnNoisyCollectionChanged(IEnumerable`1 oldItems, IEnumerable`1 newItems) in c:\Users\btord\Documents\Projects\LiveCharts\WpfView\SectionsCollection.cs:Zeile 47.
>    at LiveCharts.Helpers.NoisyCollection`1.OnNoisyCollectionChanged(IEnumerable`1 olditems, IEnumerable`1 newItems) in c:\Users\btord\Documents\Projects\LiveCharts\Core40\Helpers\NoisyCollection.cs:Zeile 592.
>    at LiveCharts.Helpers.NoisyCollection`1.Clear() in c:\Users\btord\Documents\Projects\LiveCharts\Core40\Helpers\NoisyCollection.cs:Zeile 483.

2. When I instead bind the Sections in XAML to `var SectionCollection {get;} = new Observable<AxisCollection>();` and use that the same way I get an ArgumentNullException right at the start, even in the designer. Below is the stacktrace from the designer. It didn't show me the stacktrace when the exception was thrown in runtime.

>    at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
>    at LiveCharts.Wpf.Axis.AsCoreElement(ChartCore chart, AxisOrientation source)
>    at LiveCharts.Wpf.Charts.Base.Chart.<>c__DisplayClass8.<MapXAxes>b__7(Axis x)
>    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
>    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
>    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
>    at LiveCharts.Wpf.Charts.Base.Chart.MapXAxes(ChartCore chart)
>    at LiveCharts.ChartUpdater.Update(Boolean restartsAnimations, Boolean force)
>    at LiveCharts.Wpf.Components.ChartUpdater.UpdaterTick(Boolean restartView, Boolean force)
>    at LiveCharts.Wpf.Components.ChartUpdater.OnTimerOnTick(Object sender, EventArgs args)
>    at System.Windows.Threading.DispatcherTimer.FireTick(Object unused)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>0.9.7 (WPF)</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>4.6.1</td>
</tr>
<tr>
    <td>Windows</td>
    <td>7 (64-bit)</td>
</tr>
</table>

**Comment by Mrxx99** [comment]
As a workaround I'm calling sections.clear inside a try catch:
```
            try
            {
                axisX.Sections.Clear();
            }
            catch
            {

            }
```
which works, the sections even get cleared, but I guess will impact performance
