### ISSUE TITLE
Crash when binding Visibilty of StackedRowSeries

### ISSUE THREAD

**Issue by Mrxx99** [Live-Charts/Live-Charts#858]
#### How to reproduce?

Here is my minimal code example that produces the crash reproducible:

MainWindow.xaml:

```
<Window x:Class="WpfApp1.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:lvc="clr-namespace:LiveCharts.Wpf;assembly=LiveCharts.Wpf"
        xmlns:local="clr-namespace:WpfApp1"
        mc:Ignorable="d" d:DataContext="{d:DesignInstance local:MainWindow}"
        Title="MainWindow" Height="450" Width="800">
    <Window.Resources>
        <BooleanToVisibilityConverter x:Key="BoolToVisibilty"/>
    </Window.Resources>
    <DockPanel>
        <CheckBox Content="series1" IsChecked="{Binding IsSeries1Visible}" DockPanel.Dock="Top"/>
        <lvc:CartesianChart>
            <lvc:CartesianChart.Series>
                <lvc:StackedRowSeries Values="1,2,3,4" Visibility="{Binding IsSeries1Visible, Converter={StaticResource BoolToVisibilty}}"/>
            </lvc:CartesianChart.Series>
        </lvc:CartesianChart>
    </DockPanel>
</Window>
```

MainWindow.xaml.cs:

```
    public partial class MainWindow : Window, INotifyPropertyChanged
    {
        public MainWindow()
        {
            InitializeComponent();
            DataContext = this;
        }

        private bool isSeries1Visible = true;
        public bool IsSeries1Visible
        {
            get { return isSeries1Visible; }
            set { isSeries1Visible = value; OnPropertyChanged(); }
        }

        public event PropertyChangedEventHandler PropertyChanged;

        public void OnPropertyChanged([CallerMemberName] string propertyName = "")
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }
    }
```

When you run this and uncheck the visibilty with the checkbox, the application crashes and gives the following error:

```
System.ArgumentException
  HResult=0x80070057
  Message = "NaN" is not a valid value for the property "To".
  Source = WindowsBase
  Stacktrace:
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValueInternal(DependencyProperty dp, Object value)
   at System.Windows.Media.Animation.DoubleAnimation..ctor(Double toValue, Duration duration)
   at LiveCharts.Wpf.Components.AxisSeparatorElement.Move(ChartCore chart, AxisCore axis, AxisOrientation direction, Int32 axisIndex, Double toLabel, Double toLine, Double tab)
   at LiveCharts.AxisCore.UpdateSeparators(AxisOrientation source, ChartCore chart, Int32 axisIndex)
   at LiveCharts.Charts.ChartCore.CalculateComponentsAndMargin()
   at LiveCharts.Charts.CartesianChartCore.PrepareAxes()
   at LiveCharts.ChartUpdater.Update(Boolean restartsAnimations, Boolean force)
   at LiveCharts.Wpf.Components.ChartUpdater.UpdaterTick(Boolean restartView, Boolean force)
   at LiveCharts.Wpf.Components.ChartUpdater.OnTimerOnTick(Object sender, EventArgs args)
   at System.Windows.Threading.DispatcherTimer.FireTick(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at WpfApp1.App.Main()
```

#### Extra notes

Same setup only changing from StackedRowSeries to StackedColumnSeries works fine.
And it only crashes if there is no other series to display when unchecking. For Example if you have more StackedRowSeries it only crashes if all are unchecked, if you have a different series (not StackedRow) left and then uncheck this too it also will not crash. Only if a StackedRowSeries was the only visible.
Reproduced on two different computers. With Visual Studio 2015 and 2017.

#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>0.9.7 (WPF)</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>4.6.1</td>
</tr>
<tr>
    <td>Windows</td>
    <td>7 & 10</td>
</tr>
</table>

**Comment by Mrxx99** [comment]
Just tested latest git version (master branch) and the issue is not present there. So I will close this issue.

**Comment by Mrxx99** [comment]
A workaround if someone has the problem and wants keep using the nuget version:
add an empty RowSeries that's always there
```
        <lvc:CartesianChart>
            <lvc:CartesianChart.Series>
                <lvc:RowSeries Fill="Transparent"/>
                <lvc:StackedRowSeries Values="1,2,3,4" Visibility="{Binding IsSeries1Visible, Converter={StaticResource BoolToVisibilty}}"/>
            </lvc:CartesianChart.Series>
        </lvc:CartesianChart>
```
