### ISSUE TITLE
One axis has an invalid range...

### ISSUE THREAD

**Issue by JeremiSharkboy** [Live-Charts/Live-Charts#885]
i'v got an exception: 

> LiveCharts.Helpers.LiveChartsException
  HResult=0x80131500
  Message=One axis has an invalid range, it is or it is tends to zero, please ensure your axis has a valid range
  Source=LiveCharts
  StackTrace:
   at LiveCharts.Charts.CartesianChartCore.PrepareAxes()
   at LiveCharts.ChartUpdater.Update(Boolean restartsAnimations, Boolean force)
   at LiveCharts.Wpf.Components.ChartUpdater.UpdaterTick(Boolean restartView, Boolean force)
   at LiveCharts.Wpf.Components.ChartUpdater.OnTimerOnTick(Object sender, EventArgs args)
   at System.Windows.Threading.DispatcherTimer.FireTick(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at Air_Control_System.App.Main()

My chart:
```
<lvc:CartesianChart
                        Grid.Column="1"
                        Margin="0"
                        DataTooltip="{x:Null}"
                        DisableAnimations="True"
                        Hoverable="False"
                        Series="{Binding RamValues}">
                      
                    </lvc:CartesianChart>
```

My VM:

```
 public class PcHealthViewModel : Base
    {

        public int CpuCounter { get; set; }
        public int RamCounter { get; set; }

        public bool IsHot { get; set; } = true;

        public long MaxRam { get; set; } = 0;


        public SeriesCollection RamValues { get; set; } = new SeriesCollection()
        {
             new StackedAreaSeries
                {
                    Title = "RAM",
                    Values = new ChartValues<DateTimePoint>(),
                    ScalesXAt=0,
                    ScalesYAt=0,

                                 PointForeground = Brushes.Red,
                                 LineSmoothness=0,
                                

                },
            
        };
        public SeriesCollection CpuValues { get; set; } = new SeriesCollection()
        {
             new StackedAreaSeries
                {
                    Title = "CPU",
                    Values = new ChartValues<int>(),
                    ScalesXAt=0,
                    ScalesYAt=0,

                                 PointForeground = Brushes.Gray,
                                 LineSmoothness=0

                }

        };

        public PcHealthViewModel()
        {
            try
            {

                var cpuCounter = new PerformanceCounter("Processor", "% Processor Time", "_Total");
                var ramCounter = new PerformanceCounter("Memory", "Available MBytes");




                long memKb;
                GetPhysicallyInstalledSystemMemory(out memKb);


                MaxRam = memKb / 1024;

                var val = new DateTimePoint(DateTime.UtcNow.ToLocalTime(), 2303.1);

                for (int i=0;i<61;i++)
                {
                    //CpuValues[0]?.Values?.Add(0);
                    RamValues[0]?.Values?.Add(val);
                }


                //Task.Factory.StartNew(async () =>
                //{
                //    while (true)
                //    {

                //        CpuCounter = (int)cpuCounter.NextValue();
                //        RamCounter =  (int)MaxRam- (int)ramCounter.NextValue();

                //        await Application.Current.Dispatcher.InvokeAsync(() =>
                //        {
                //            try
                //            {
                //                CpuValues[0]?.Values?.Add(CpuCounter);
                //                RamValues[0]?.Values?.Add(RamCounter);


                //                if (CpuValues[0]?.Values?.Count > 60)
                //                {
                //                    CpuValues[0]?.Values?.RemoveAt(0);
                //                    RamValues[0]?.Values?.RemoveAt(0);

                //                }
                //            }
                //            catch (Exception ex)
                //            {
                //                var a = "";
                //            }
                //        });

                //        await Task.Delay(1000);

                //    }
                //});
            }
            catch(Exception ex)
            {
                var a = "";
            }
        }

        [DllImport("kernel32.dll")]
        [return: MarshalAs(UnmanagedType.Bool)]
        static extern bool GetPhysicallyInstalledSystemMemory(out long TotalMemoryInKilobytes);


    }
```

I'm using:
LiveCharts wpf 0.9.7
.net 4.7.2
windows 10 1809

i can share my project if need

**Comment by rmorgan001** [comment]
was there an answer for this #885?
