### ISSUE TITLE
The invocation of the constructor on type 'LiveCharts.Wpf.CartesianChart' that matches the specified binding constraints threw an exception.

### ISSUE THREAD

**Issue by vijayshinva** [Live-Charts/Live-Charts#964]
#### How to reproduce?
A simple CandleSeries chart crashes randomly during InitializeComponent() of the WPF form with the exception 

`'The invocation of the constructor on type 'LiveCharts.Wpf.CartesianChart' that matches the specified binding constraints threw an exception.' Line number '167' and line position '26'.

   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at TestLiveCharts.TestWindow.InitializeComponent() in D:\Test\Test\src\Test\TestWindow.xaml:line 1`

and an inner exception 

`Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index

   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
   at System.IO.Packaging.PackagePart.CleanUpRequestedStreamsList()
   at System.IO.Packaging.PackagePart.GetStream(FileMode mode, FileAccess access)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at LiveCharts.Wpf.Charts.Base.Chart..ctor() in c:\Users\btord\Documents\Projects\LiveCharts\WpfView\Charts\Base\Chart.cs:line 82
   at LiveCharts.Wpf.CartesianChart..ctor() in c:\Users\btord\Documents\Projects\LiveCharts\WpfView\CartesianChart.cs:line 40`

The chart is defined as follows

`<lvc:CartesianChart x:Name="candleChart" Padding="0" Margin="0" Height="360" Grid.Row="0">
	<lvc:CartesianChart.Series>
		<lvc:CandleSeries Title="CandleChart" Values="{Binding ChartValuesCandle}"/>
	</lvc:CartesianChart.Series>
	<lvc:CartesianChart.AxisX>
		<lvc:Axis LabelsRotation="20" Labels="{Binding LabelsCandle}"/>
	</lvc:CartesianChart.AxisX>
	<lvc:CartesianChart.AxisY>
		<lvc:Axis x:Name="candleAxis" Title="Price">
		</lvc:Axis>
	</lvc:CartesianChart.AxisY>
</lvc:CartesianChart>`

And the ChartValuesCandle collection is defined as 

#### Extra notes

Not sure which list is throwing the OutOfRange exception. 

#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>0.9.7</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>4.7.2</td>
</tr>
<tr>
    <td>Windows</td>
    <td>10</td>
</tr>
</table>

**Comment by vijayshinva** [comment]
The same code sometimes throws a slightly different exception

`Object reference not set to an instance of an object.

   at System.IO.Packaging.PackagePart.CleanUpRequestedStreamsList()
   at System.IO.Packaging.PackagePart.GetStream(FileMode mode, FileAccess access)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at LiveCharts.Wpf.DefaultTooltip..ctor() in c:\Users\btord\Documents\Projects\LiveCharts\WpfView\DefaultTooltip.xaml.cs:line 47
   at LiveCharts.Wpf.Charts.Base.Chart..ctor() in c:\Users\btord\Documents\Projects\LiveCharts\WpfView\Charts\Base\Chart.cs:line 83
   at LiveCharts.Wpf.CartesianChart..ctor() in c:\Users\btord\Documents\Projects\LiveCharts\WpfView\CartesianChart.cs:line 40`


In both cases it seems to fail in System.IO.Packaging.PackagePart.CleanUpRequestedStreamsList()
